### ISSUE TITLE
Wrong time format

### ISSUE THREAD

**Issue by dennis-adamczyk** [JaeYeopHan/gatsby-post-gen#4]
## Description
In `lib/index.js` you define the date/time format as `const DATE_FORMAT = 'yyyy-MM-dd HH:MM:SS'`.
Because the big M means month, you have to change it to:
`const DATE_FORMAT = 'yyyy-MM-dd HH:mm:ss'`

**Comment by jbee37142** [comment]
fixed https://github.com/JaeYeopHan/gatsby-post-gen/pull/5
